"""add_geo_columns

Revision ID: 126b357f3fe9
Revises: 9478d39675a3
Create Date: 2026-07-15 18:18:25.462030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "126b357f3fe9"
down_revision: Union[str, Sequence[str], None] = "9478d39675a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ml_dataset", sa.Column("address", sa.String(length=512), nullable=True)
    )
    op.add_column("ml_dataset", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column("ml_dataset", sa.Column("longitude", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ml_dataset", "longitude")
    op.drop_column("ml_dataset", "latitude")
    op.drop_column("ml_dataset", "address")
    # ### end Alembic commands ###
