"""add_pgvector

Revision ID: 367cb813f931
Revises: 6d169b75ca9e
Create Date: 2026-07-15 01:20:17.827261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "367cb813f931"
down_revision: Union[str, Sequence[str], None] = "6d169b75ca9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apartment_images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("apartment_id", sa.String(length=255), nullable=False),
        sa.Column("image_path", sa.String(length=512), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["apartment_id"], ["ml_dataset.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "ml_dataset",
        sa.Column("is_duplicate", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "ml_dataset", sa.Column("duplicate_of_id", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ml_dataset", "duplicate_of_id")
    op.drop_column("ml_dataset", "is_duplicate")
    op.drop_table("apartment_images")
    # ### end Alembic commands ###
