"""add_apartment_details

Revision ID: 6d169b75ca9e
Revises: eb18f3fdea03
Create Date: 2026-07-12 21:16:00.351975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d169b75ca9e"
down_revision: Union[str, Sequence[str], None] = "eb18f3fdea03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ml_dataset", sa.Column("total_area", sa.Float(), nullable=True))
    op.add_column("ml_dataset", sa.Column("floor", sa.Integer(), nullable=True))
    op.add_column("ml_dataset", sa.Column("total_floors", sa.Integer(), nullable=True))
    op.add_column("ml_dataset", sa.Column("deposit", sa.Integer(), nullable=True))
    op.add_column(
        "ml_dataset", sa.Column("renovation", sa.String(length=50), nullable=True)
    )
    op.add_column("ml_dataset", sa.Column("metadata_json", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ml_dataset", "metadata_json")
    op.drop_column("ml_dataset", "renovation")
    op.drop_column("ml_dataset", "deposit")
    op.drop_column("ml_dataset", "total_floors")
    op.drop_column("ml_dataset", "floor")
    op.drop_column("ml_dataset", "total_area")
    # ### end Alembic commands ###
