"""add seller id

Revision ID: 7e0ea016bb8b
Revises: 126b357f3fe9
Create Date: 2026-07-15 18:46:53.575542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e0ea016bb8b"
down_revision: Union[str, Sequence[str], None] = "126b357f3fe9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ml_dataset", sa.Column("seller_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "ml_dataset",
        sa.Column(
            "is_ai_generated", sa.Boolean(), server_default="false", nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ml_dataset", "is_ai_generated")
    op.drop_column("ml_dataset", "seller_id")
    # ### end Alembic commands ###
