"""images_path to unique

Revision ID: 9478d39675a3
Revises: 367cb813f931
Create Date: 2026-07-15 01:39:28.694989

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9478d39675a3"
down_revision: Union[str, Sequence[str], None] = "367cb813f931"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "apartment_images", ["image_path"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "apartment_images", type_="unique")
    # ### end Alembic commands ###
